//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractors
    {
        public int keyId { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public Nullable<int> ContractorTypeId { get; set; }
        public string Phone { get; set; }
    
        public virtual ContractorType ContractorType { get; set; }
    }
}
